name: Stand By Me
favicon: null
layout_spectrum: 0.36598961148411036
typography_spectrum: 0.7302456269972026
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.32551242783665657
  lightness: 0.9747066088020802
  saturation: 0.9472737794276327
  rhythmicContrast: 0.467373053310439
purpose: []
